#ifndef PAGE_TYPE
#define PAGE_TYPE


typedef enum {
    ROLE_NONE,
    ROLE_ADMIN,
    ROLE_CASHIER,
    ROLE_SALES
} Role;

typedef enum {
    HAL_LANDING,

    HAL_LOGIN, 

    HAL_DASHBOARD_ADMIN,
    HAL_DASHBOARD_CASHIER,
    HAL_DASHBOARD_SALES,

    HAL_CASHIER_CUSTOMERS,

    HAL_CASHIER_DATA_PELANGGAN,
    HAL_CASHIER_PENJUALAN_MOBIL,
    HAL_CASHIER_PENJUALAN_AKSESORIS,
    HAL_CASHIER_INPUT_PENJUALAN_AKSESORIS, 
    HAL_CASHIER_INPUT_PENJUALAN_MOBIL,

    HAL_SALES_TEST_DRIVE,
    HAL_SALES_DATA_PELANGGAN,                

    HAL_ADMIN_M_MOBIL,
    HAL_ADMIN_M_AKSESORIS,
    HAL_ADMIN_M_KARYAWAN,
    HAL_ADMIN_M_PELANGGAN,

    HAL_ADMIN_EMPLOYEE_DATA,

    HAL_ADMIN_L_PENJUALAN,
    HAL_ADMIN_L_TEST_DRIVE,

    HAL_EXIT
} Halaman;

#endif